### PR TITLE
added favicon + link to favicon

### PR DESCRIPTION
**Pull request by SkylerAl**
Just switched the links for the read me

### CODE REVIEW

**Comment by azuryte5** [comment]
oh I like this. How did you add it as a draft?

**Comment by SkylerAl** [comment]
> oh I like this. How did you add it as a draft?

When your creating the Pull request, you can specify that you want it to be a draft (Which means that the branch is still being worked on and the PR is not ready to be reviewed yet)

**Comment by SkylerAl** [comment]
Also added an icon for the tab bar as well as the readme link switch

**Review by azuryte5 — COMMENTED** [review]
What folder is the favicon.png located in?

thanks for picking one and adding an icon

**Comment by SkylerAl** [comment]
> What folder is the favicon.png located in?

My bad, didnt catch this. I believe it was just added separetely into the project folder, should it be somewhere specific?

**Comment by azuryte5** [comment]
no worries, images should be in the assets/img folder if possible

**Review by azuryte5 — APPROVED** [review]
looks good to me! thanks

**Pull request merged**
